version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db_nest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pg_db_test
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data_nest:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    container_name: mongo_db_dev
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    container_name: mongo_express_dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8099:8081

volumes:
  mongodb_data:
  postgres_data_nest: