version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: nest-cars
    container_name: nest_cars
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: dev
      PORT: 3000
    command: yarn start:dev
    #command: yarn start:debug:docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

