version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-cars
    container_name: nest_cars
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}